name: Continuous integration
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 1,15 * *"

# In the event that there is a new push to the ref, cancel any running jobs because there are now obsolete, and wasting resources.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        mlua: [mlua/lua54,mlua/lua53,mlua/lua52,mlua/lua51,mlua/luajit]

    steps:
      - name: Install Rust environment
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.OS }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-cargo-
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Build library
        run: cargo build --features ${{ matrix.mlua }},mlua/vendored
      - name: Run test suite
        run: cargo test --features ${{ matrix.mlua }},mlua/vendored
